install_root refactoring, formating, error handling and multi-arch rpms files

diff --git a/ts/bin/install_chroot b/ts/bin/install_chroot
--- a/ts/bin/install_chroot
+++ b/ts/bin/install_chroot
@@ -3,20 +3,41 @@
 # URL: http://www.thinstation.org
 # Maintainer: Donald A. Cupp Jr. (don cupp jr at ya hoo dot com)
 
-core_ports="`grep -v '^\s*#' ts/rpms/core |sed ':a;N;$!ba;s/\n/ /g'`"
-grub_ports="`grep -v '^\s*#' ts/rpms/grub |sed ':a;N;$!ba;s/\n/ /g'`"
-kernel_ports="`grep -v '^\s*#' ts/rpms/kernel |sed ':a;N;$!ba;s/\n/ /g'`"
-firmware_ports="`grep -v '^\s*#' ts/rpms/firmware |sed ':a;N;$!ba;s/\n/ /g'`"
-uboot_ports="uboot-tools"
-system_ports="`grep -v '^\s*#' ts/rpms/system |sed ':a;N;$!ba;s/\n/ /g'`"
-ts_ports="`grep -v '^\s*#' ts/rpms/ts |sed ':a;N;$!ba;s/\n/ /g'`"
-if [ -e ts/rpms/other ]; then
-	other_ports="`grep -v '^\s*#' ts/rpms/other |sed ':a;N;$!ba;s/\n/ /g'`"
+DNF_INSTALL="dnf install --setopt=keepcache=1 --releasever=42"
+
+if [ -z "$DEBUG" ] || [ "$DEBUG" != "true" ]; then
+	DNF_INSTALL="$DNF_INSTALL -y"
 fi
 
-stage1()
-{
-	if dnf --version| head -n1 |grep -qe dnf5; then
+# Set target architecture if not already set
+if [ -z "$TARGET_ARCH" ]; then
+	TARGET_ARCH=$(uname -m)
+fi
+
+# Build dnf options according to target architecture
+if [ -n "$CROSS_COMPILE" ] && [ "$CROSS_COMPILE" == "true" ]; then
+	DNF_INSTALL="$DNF_INSTALL --forcearch=$TARGET_ARCH"
+fi
+
+## Function to read package lists from files in ts/rpms and return a space-separated list of packages
+## syntax: get_rpms <file1> <file2> ...
+get_rpms() {
+	ports=""
+	until [ -z "$1" ] ; do
+		if [ -e ts/rpms/$1 ]; then
+			ports="$ports $(grep -v '^\s*#' ts/rpms/$1 | sed ':a;N;$!ba;s/\n/ /g')"
+		fi
+		if [ -e ts/rpms/$1-$TARGET_ARCH ]; then
+			ports="$ports $(grep -v '^\s*#' "ts/rpms/$1-$TARGET_ARCH" | sed ':a;N;$!ba;s/\n/ /g')"
+		fi
+		shift
+	done
+	echo -n $ports
+}
+
+stage1() {
+	echo "STAGE 1: Installing core packages"
+	if dnf --version | head -n1 | grep -qe dnf5; then
 		host_config="--use-host-config"
 		xfce=xfce-desktop
 	else
@@ -27,8 +48,8 @@ stage1()
 	chown -R root:root ts setup-chroot README.md
 
 	for dir in proc sys home dev mnt downloads var/cache/dnf; do
-		if [ ! -e $dir ] ; then
-				mkdir -p -m 755 $dir
+		if [ ! -e $dir ]; then
+			mkdir -p -m 755 $dir
 		fi
 	done
 
@@ -39,151 +60,148 @@ stage1()
 		mkdir -m 750 root
 	fi
 
-        if ! mountpoint dev >/dev/null 2>&1 ; then mount --bind /dev dev ; fi
-        if ! mountpoint tmp >/dev/null 2>&1 ; then mount -t tmpfs /tmp tmp ; fi
-        if ! mountpoint proc >/dev/null 2>&1 ; then mount -t proc proc proc ; fi
-        if ! mountpoint sys >/dev/null 2>&1 ; then mount -t sysfs none sys ; fi
+	if ! mountpoint dev >/dev/null 2>&1; then mount --bind /dev dev; fi
+	if ! mountpoint tmp >/dev/null 2>&1; then mount -t tmpfs /tmp tmp; fi
+	if ! mountpoint proc >/dev/null 2>&1; then mount -t proc proc proc; fi
+	if ! mountpoint sys >/dev/null 2>&1; then mount -t sysfs none sys; fi
 
-	# Build dnf options according to target architecture
-	DNF_ARCH_OPTS=""
-	ARCH_SPECIFIC_PORTS=""
-	if [ -n "$TARGET_ARCH" ] && [ "$TARGET_ARCH" != "$(uname -m)" ]; then
-		DNF_ARCH_OPTS="--forcearch=$TARGET_ARCH"
-		echo "Using dnf --forcearch=$TARGET_ARCH"
-		# Architecture-specific packages
-		case "$TARGET_ARCH" in
-			aarch64|armv7l)
-				echo "Adding U-Boot tools for ARM, skipping x86_64-specific grub and firmware packages"
-				ARCH_SPECIFIC_PORTS="$uboot_ports"
-				;;
-			*)
-				ARCH_SPECIFIC_PORTS="$grub_portss"
-				;;
-		esac
-	else
-		ARCH_SPECIFIC_PORTS="$grub_ports"
-	fi
-	
 	ROOT=$PWD
-	dnf install --setopt=keepcache=1 -y --installroot=$ROOT $host_config --releasever=42 $DNF_ARCH_OPTS --skip-unavailable $core_ports $kernel_ports $firmware_ports $ARCH_SPECIFIC_PORTS
+
+	if ! $DNF_INSTALL --installroot=$ROOT $host_config $(get_rpms core kernel boot firmware) ; then
+		echo "Failed to install core packages. Exiting."
+		echo "Command was: $DNF_INSTALL --installroot=$ROOT $host_config $(get_rpms core kernel boot firmware)"
+		exit 1
+	fi
 	cd $ROOT
 	touch $ROOT/dostage2
 }
 
-stage2()
-{
-#	exclude=`echo "$core_ports"|sed -e 's/ /\/\|/g'`
-#	mkdir -p /var/lib/pkg
-#	procs=`nproc`
-#	let procs-=1
-#	for Root in $ROOT/ts $XTRWRKNG; do
-#		find -L $Root/ports -name Pkgfile | \
-#		grep -Ev "nocache|proprietary|binary-core|binary-opt|relegated" | \
-#		grep -Ev "$exclude" | \
-#		xargs -n 1 -P $procs -I {} bash -c 'install_port "$@"' _ {}
-#	done
-#	for core_port in $core_ports; do
-#              	Pkgfile=/ts/ports/core/$core_port/Pkgfile
-#		install_port $Pkgfile
-#	done
-#	add_to_db
-#	printf "\rPort Installation %-40s\n" "Complete"
-#	printf "\rRunning the pre and post install scripts\n"
-#	post_install
-#	printf "\rPort Install scripts %-40s\n" "Complete"
+stage2() {
+	echo "STAGE 2: Installing ports"
+	#	exclude=`echo "$core_ports"|sed -e 's/ /\/\|/g'`
+	#	mkdir -p /var/lib/pkg
+	#	procs=`nproc`
+	#	let procs-=1
+	#	for Root in $ROOT/ts $XTRWRKNG; do
+	#		find -L $Root/ports -name Pkgfile | \
+	#		grep -Ev "nocache|proprietary|binary-core|binary-opt|relegated" | \
+	#		grep -Ev "$exclude" | \
+	#		xargs -n 1 -P $procs -I {} bash -c 'install_port "$@"' _ {}
+	#	done
+	#	for core_port in $core_ports; do
+	#              	Pkgfile=/ts/ports/core/$core_port/Pkgfile
+	#		install_port $Pkgfile
+	#	done
+	#	add_to_db
+	#	printf "\rPort Installation %-40s\n" "Complete"
+	#	printf "\rRunning the pre and post install scripts\n"
+	#	post_install
+	#	printf "\rPort Install scripts %-40s\n" "Complete"
 	rm /dostage2
 	touch /dostage3
 }
 
-stage3()
-{
+stage3() {
+	echo "STAGE 3: Installing packages and populating tools"
 	cp -a /ts/repos/* /etc/yum.repos.d/.
 	dnf makecache
-        dnf install --setopt=keepcache=1 -y --releasever=42 $DNF_ARCH_OPTS --skip-unavailable $system_ports
-	dnf install --setopt=keepcache=1 -y --allowerasing $DNF_ARCH_OPTS $ts_ports $other_ports
+
+	echo "Installing system packages"
+	if ! $DNF_INSTALL $(get_rpms system); then
+		echo "Failed to install system packages. Exiting."
+		echo "Command was: $DNF_INSTALL $(get_rpms system)"
+		exit 1
+	fi
+
+	echo "Installing TS packages"
+	if ! $DNF_INSTALL --allowerasing $(get_rpms ts other); then
+		echo "Failed to install TS packages. Exiting."
+		echo "Command was: $DNF_INSTALL --allowerasing $(get_rpms ts other)"
+		exit 1
+	fi
 	for Root in $TSWRKNG $XTRWRKNG; do
-		if [ $Root = $TSWRKNG ]
-			then export Cache=/ts
-			else export Cache=$Root
+		if [ $Root = $TSWRKNG ]; then
+			export Cache=/ts
+		else
+			export Cache=$Root
 		fi
 		export Root
-		procs=`nproc`
-                let procs-=1
-		ls --color=never $Root/packages |xargs -P $procs -I {} bash -c 'unwind_package "$@"' _ {}
+		procs=$(nproc)
+		let procs-=1
+		ls --color=never $Root/packages | xargs -P $procs -I {} bash -c 'unwind_package "$@"' _ {}
 	done
 	printf "\rPackage Population %-40s\n" "Complete"
 	echo "Populating tools"
 	update -t
 	cd $TSWRKNG
 	./build --regenconf
-	if [ ! -e /build ] ; then
+	if [ ! -e /build ]; then
 		ln -sf ts/build /build
 	fi
 	rm /dostage3
 	touch /dostage4
 }
 
-unwind_package()
-{
+unwind_package() {
 	pkg=$1
 	printf "\rPopulating Package %-40s" "$pkg"
-        cd $Root/packages/$pkg
-        if [ -e .unwind ]; then
-        	if cat .unwind |grep -e "#" |cut -d "#" -f2 |md5sum -c --quiet ; then
-                	. .unwind
-                else
-                       	update $pkg
-                fi
-        else
-              	update $pkg
-        fi
+	cd $Root/packages/$pkg
+	if [ -e .unwind ]; then
+		if cat .unwind | grep -e "#" | cut -d "#" -f2 | md5sum -c --quiet; then
+			. .unwind
+		else
+			update $pkg
+		fi
+	else
+		update $pkg
+	fi
 }
 
-stage4()
-{
+stage4() {
 	rm /dostage4
-#	printf "\rLooking at core binary ports\n"
-#	procs=`nproc`
-#        let procs-=1
-#        for Root in $ROOT/ts $XTRWRKNG; do
-#                find -L $Root/ports -name Pkgfile | \
-#                grep -E "binary-core" | \
-#                xargs -n 1 -P $procs -I {} bash -c 'install_binary_port "$@"' _ {}
-#        done
-#        # Fix for db access violations
-#        if [ -e /var/log/pkgbuild ]; then
-#                for prt in `ls /var/log/pkgbuild -1`; do
-#                        prt-get install `basename $prt .log` -if -im -ns > /dev/null 2>&1
-#                done
-#        fi
-#	add_to_db
-#        printf "\rBinary Core Port Installation %-40s\n" "Complete"
-#	post_install
+	#	printf "\rLooking at core binary ports\n"
+	#	procs=`nproc`
+	#        let procs-=1
+	#        for Root in $ROOT/ts $XTRWRKNG; do
+	#                find -L $Root/ports -name Pkgfile | \
+	#                grep -E "binary-core" | \
+	#                xargs -n 1 -P $procs -I {} bash -c 'install_binary_port "$@"' _ {}
+	#        done
+	#        # Fix for db access violations
+	#        if [ -e /var/log/pkgbuild ]; then
+	#                for prt in `ls /var/log/pkgbuild -1`; do
+	#                        prt-get install `basename $prt .log` -if -im -ns > /dev/null 2>&1
+	#                done
+	#        fi
+	#	add_to_db
+	#        printf "\rBinary Core Port Installation %-40s\n" "Complete"
+	#	post_install
 }
 
-update_db()
-{
-	for db in `find /tmp/ -name \*.db`; do
-                cat $db >> /var/lib/pkg/db
-                echo "" >> /var/lib/pkg/db
+update_db() {
+	for db in $(find /tmp/ -name \*.db); do
+		cat $db >>/var/lib/pkg/db
+		echo "" >>/var/lib/pkg/db
 		rm $db
-        done
+	done
 }
 
-install_binary_port()
-{
+install_binary_port() {
 	Pkgfile=$1
 	if ! install_port $Pkgfile; then
-		port_name=`echo $Pkgfile |cut -d "/" -f6`
+		port_name=$(echo $Pkgfile | cut -d "/" -f6)
 		if ! $AUTODL; then
 			answered=false
 			while ! $answered; do
 				printf "Would you like to try and build it now? Y/N:"
 				read -n 1 answer
 				case $answer in
-					Y|y) prt-get install -fr -if -im -is -ns $port_name;answered=true;;
-					n|n) answered=true;;
-					*) answered=false;;
+				Y | y)
+					prt-get install -fr -if -im -is -ns $port_name
+					answered=true
+					;;
+				n | n) answered=true ;;
+				*) answered=false ;;
 				esac
 			done
 		else
@@ -193,29 +211,28 @@ install_binary_port()
 	fi
 }
 
-install_port()
-{
+install_port() {
 	Pkgfile=$1
 	. $Pkgfile
-	port_dir=`dirname $Pkgfile`
-	port_name=`basename $port_dir`
-	pkg_name="`find -L $port_dir -type f -name ${name}#${version}-${release}.pkg.tar.\* -printf '%f'`"
-	if [ -n "$XTRWRKNG" ] \
-	&& [ -e "$XTRWRKNG/${port_dir##//ts/}" ]; then
+	port_dir=$(dirname $Pkgfile)
+	port_name=$(basename $port_dir)
+	pkg_name="$(find -L $port_dir -type f -name ${name}#${version}-${release}.pkg.tar.\* -printf '%f')"
+	if [ -n "$XTRWRKNG" ] &&
+		[ -e "$XTRWRKNG/${port_dir##//ts/}" ]; then
 		return 0
 	else
-	printf "\rInstalling Port %-40s" "$port_name"
+		printf "\rInstalling Port %-40s" "$port_name"
 		if [ -f $port_dir/$pkg_name ]; then
-			echo $name > /tmp/$name.db
-			echo $version-$release >> /tmp/$name.db
-			tar -hxvf $port_dir/$pkg_name -C / >> /tmp/$name.db 2>/dev/null #|| rm /tmp/$name.db && echo "$pkg_name failed"
+			echo $name >/tmp/$name.db
+			echo $version-$release >>/tmp/$name.db
+			tar -hxvf $port_dir/$pkg_name -C / >>/tmp/$name.db 2>/dev/null #|| rm /tmp/$name.db && echo "$pkg_name failed"
 			if [ -e $port_dir/pre-install ]; then
-#				echo "echo $port_name pre" >> $ROOT/post-install.sh
-				echo ". $port_dir/pre-install || echo \"$port_name pre-install failed!\" && true" >> $ROOT/post-install.sh
+				#				echo "echo $port_name pre" >> $ROOT/post-install.sh
+				echo ". $port_dir/pre-install || echo \"$port_name pre-install failed!\" && true" >>$ROOT/post-install.sh
 			fi
 			if [ -e $port_dir/post-install ]; then
-#				echo "echo $port_name post" >> $ROOT/post-install.sh
-				echo ". $port_dir/post-install || echo \"$port_name post-install failed!\" && true" >> $ROOT/post-install.sh
+				#				echo "echo $port_name post" >> $ROOT/post-install.sh
+				echo ". $port_dir/post-install || echo \"$port_name post-install failed!\" && true" >>$ROOT/post-install.sh
 			fi
 			return 0
 		else
@@ -225,17 +242,15 @@ install_port()
 	fi
 }
 
-add_to_db()
-{
-	for db in `find /tmp/ -name \*.db`; do
-                cat $db >> /var/lib/pkg/db
-                echo "" >> /var/lib/pkg/db
+add_to_db() {
+	for db in $(find /tmp/ -name \*.db); do
+		cat $db >>/var/lib/pkg/db
+		echo "" >>/var/lib/pkg/db
 		rm $db
-        done
+	done
 }
 
-post_install()
-{
+post_install() {
 	if [ -e /post-install.sh ]; then
 		source /post-install.sh
 		rm /post-install.sh
@@ -252,11 +267,11 @@ fi
 
 ROOT=$PWD
 if [ -e $ROOT/dostage4 ]; then
-		stage4
-	elif [ -e $ROOT/dostage3 ]; then
-		stage3
-	elif [ -e $ROOT/dostage2 ]; then
-		stage2
-	else
-		stage1
+	stage4
+elif [ -e $ROOT/dostage3 ]; then
+	stage3
+elif [ -e $ROOT/dostage2 ]; then
+	stage2
+else
+	stage1
 fi
