modified:   ts/bin/repackage 	modified:   ts/build/build 	modified:   ts/build/fastboot/bin-boot 	modified:   ts/build/packages/audit/build/finalize 	modified:   ts/build/packages/audit/build/install 	modified:   ts/build/packages/base/etc/profile 	modified:   ts/build/packages/base/etc/thinstation.global 	modified:   ts/build/packages/base/init 	renamed:    ts/build/packages/selinux-policy/.dna -> ts/build/packages/coreutils/.dna 	renamed:    ts/build/packages/selinux-policy/.unwind -> ts/build/packages/coreutils/.unwind 	renamed:    ts/build/packages/selinux-policy/.wind -> ts/build/packages/coreutils/.wind 	new file:   ts/build/packages/coreutils/build/install 	new file:   ts/build/packages/coreutils/build/remove 	renamed:    ts/build/packages/selinux-policy/dependencies -> ts/build/packages/coreutils/dependencies 	deleted:    ts/build/packages/selinux-policy/build/install 	deleted:    ts/build/packages/selinux-policy/build/remove 	new file:   ts/build/packages/selinux/.dna 	new file:   ts/build/packages/selinux/.unwind 	new file:   ts/build/packages/selinux/.wind 	new file:   ts/build/packages/selinux/build/finalize 	new file:   ts/build/packages/selinux/build/install 	new file:   ts/build/packages/selinux/build/remove 	new file:   ts/build/packages/selinux/dependencies 	modified:   ts/build/packages/systemd/build/finalize 	new file:   ts/build/packages/zlib-ng-compat/.dna 	new file:   ts/build/packages/zlib-ng-compat/.unwind 	new file:   ts/build/packages/zlib-ng-compat/.wind 	new file:   ts/build/packages/zlib-ng-compat/build/install 	new file:   ts/build/packages/zlib-ng-compat/build/remove 	new file:   ts/build/packages/zlib-ng-compat/dependencies

diff --git a/ts/build/packages/base/init b/ts/build/packages/base/init
--- a/ts/build/packages/base/init
+++ b/ts/build/packages/base/init
@@ -16,20 +16,42 @@ if [ -e /proc/cmdline ]; then
 	clear
     fi
 fi
+
 # Input file where capabilities are stored
 CAP_FILE="/etc/filecaps"
+if [ -e $CAP_FILE ]; then
+	# Read each line in the CAP_FILE
+	while IFS= read -r line; do
+	    # Extract the file path and capability string using parameter expansion
+	    file_path="${line% *}"  # Everything before the last space
+	    caps="${line##* }"      # Everything after the last space
 
-# Read each line in the CAP_FILE
-while IFS= read -r line; do
-    # Extract the file path and capability string using parameter expansion
-    file_path="${line% *}"  # Everything before the last space
-    caps="${line##* }"      # Everything after the last space
+	    # Apply the capabilities to the file if the file exists
+	    if [ -n "$caps" ] && [ -e "$file_path" ]; then
+	        setcap "$caps" "$file_path"
+	    fi
+	done < "$CAP_FILE"
+fi
 
-    # Apply the capabilities to the file if the file exists
-    if [ -n "$caps" ] && [ -e "$file_path" ]; then
-        setcap "$caps" "$file_path"
-    fi
-done < "$CAP_FILE"
+# Define the input file containing the xattrs
+XATTR_FILE="/etc/filexattrs"
+if [ -e $XATTR_FILE ]; then
+	# Process each line from the attribute file
+	while IFS= read -r line; do
+	    # Extract the filename and attribute
+	    filename=$(echo "$line" | awk '{print $1}')
+	    attr=$(echo "$line" | awk '{$1=""; print substr($0, 2)}')  # Remove the first field and leading space
+
+	    # Split the attribute into name and value
+	    attr_name=$(echo "$attr" | cut -d'=' -f1)
+	    attr_value=$(echo "$attr" | cut -d'=' -f2- | tr -d '"')
+
+	    # Restore the attribute using setfattr
+	    if ! setfattr -n "$attr_name" -v "$attr_value" "$filename"; then
+        	echo "Failed to restore $attr_name for $filename"
+	    fi
+	done < "$XATTR_FILE"
+fi
 
 # Hand over control to systemd
 exec /lib64/systemd/systemd
